import mongoose from 'mongoose'

const ChunkSchema = new mongoose.Schema(
  {
    // Reference to parent Source document
    source_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Source',
      required: true,
      index: true,          // fast lookups by article
    },

    // Denormalized for prompt injection — avoids a join at query time
    source_url: {
      type: String,
      required: true,
    },
    source_category: {
      type: String,
      required: true,
    },

    // Chunk content
    content: {
      type: String,
      required: true,
    },
    chunk_index: {
      type: Number,
      required: true,       // position within original article (0-based)
    },

    // Embedding — generated by Gemini text-embedding-001 (3072 dimensions)
    embedding: {
      type: [Number],
      required: true,
    },
  },
  { timestamps: true }
)

// Fetch all chunks for one article in order
ChunkSchema.index({ source_id: 1, chunk_index: 1 })

export const Chunk = mongoose.model('Chunk', ChunkSchema)