import mongoose from 'mongoose'

const MessageSchema = new mongoose.Schema(
    {
        //user id of the sender
        sender: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'FinWise-accounts',  
            required: true
        },
        //content of the message
        content: {
            type: String,
            required: true
        },
        //chat session id to group messages into conversations
        sessionId: {
            type: String,
            required: true
        },
        //Optional field: refrence: for AI responses only: refrence the question this answers
        reference: {
            type: String,
            required: false
        },
        //Role: 'user' or 'assistant' to distinguish message type
        role: {
            type: String,
            enum: ['user', 'assistant'],
            default: 'user'
        },
        //message's own id is automatically generated by MongoDB
        
        
    },
    { timestamps: true }
)

const Message = mongoose.model('Message', MessageSchema)
export default Message